title = "Data Protection Scholars Network"
baseURL = "https://dataprotectionscholars.network"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"
resourceDir = "../resources"
copyright = "the authors"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[pagination]
pagerSize = 10
googleAnalytics = ""
enableRobotsTXT = false

[languages]
  [languages.en]
    title = "Data Protection Scholars Network"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The name says it all."
  facebook = ""
  twitter = "https://twitter.com/dataprotectionscholars"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/beep.jpg"
  recent_posts_number = 2

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
